apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-banco
spec:
  containers:
  - name: db-container
    image: mysql:5.7.19
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_DATABASE
        value: "loja"
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "1"
