apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  serviceName: db-service
  selector:
    matchLabels:
      app: db-banco
    #replicas: 2
  template:
    metadata:
      labels:
        app: db-banco
    spec:
      containers:
        - name: db-container
          image: mysql:5.7.19
          #resources:
          #  limits:
          #    memory: "128Mi"
          #    cpu: "500m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "loja"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          volumeMounts:
            - name: volume-sql
              mountPath: /var/lib/mysql
      volumes:
        - name: volume-sql
          persistentVolumeClaim:
            claimName: access-sql
