apiVersion: v1
kind: Pod
metadata:
 name: pod-volume
 labels:
  app: pod-volume
spec:
  containers:
    - name: pod-volume-container1
      image: nginx:latest
      volumeMounts:
        - mountPath: /primeiro-volume
          name: primeiro-volume
    - name: pod-volume-container2
      image: jenkins-alpine
      volumeMounts:
        - mountPath: /primeiro-volume
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath: 
        path: /home/devops/labs/k8s-2/portal-noticias/volume
        type: Directory
  
