apiVersion: v1
kind: Pod
metadata: 
  name: app-pod
spec:
  containers:
    - name: app-container
      image: rafanercessian/aplicacao-loja:v1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80